version: '3.8'
services:
  app:
    image: spring-boot-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1213
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
